version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testing_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: testing_platform
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data: